C     THE ARITHMETIC IF: THREE-WAY BRANCH ON SIGN.
C     OBSOLESCENT IN FORTRAN 90; DELETED IN FORTRAN 2018.
      PROGRAM ARIF
      INTEGER K
      K = 0
      IF (K) 10, 20, 30
   10 STOP 'NEGATIVE'
   20 STOP 'ZERO'
   30 STOP 'POSITIVE'
      END
