C     THE COMPUTED GO TO: BRANCH BY POSITION IN A LABEL LIST.
C     OBSOLESCENT SINCE FORTRAN 95; STILL IN THE STANDARD.
      PROGRAM CGOTO
      INTEGER K
      K = 2
      GO TO (10, 20, 30), K
   10 STOP 'ONE'
   20 STOP 'TWO'
   30 STOP 'THREE'
      END
