C     HOLLERITH CONSTANTS: CHARACTERS COUNTED INTO NUMERIC STORAGE.
C     FORTRAN 66 PRACTICE; REMOVED FROM THE FORTRAN 77 STANDARD.
      PROGRAM HOLLER
      INTEGER GREET(2)
      DATA GREET /4HHELO, 4H WLD/
      WRITE (*, '(2A4)') GREET
      END
