C     THE PLAIN GO TO: AN UNCONDITIONAL JUMP TO A LABEL.
C     FULLY STANDARD TO THIS DAY; MERELY OUT OF FASHION.
      PROGRAM PGOTO
      INTEGER I
      I = 0
   10 CONTINUE
      I = I + 1
      IF (I .LT. 3) GO TO 10
      WRITE (*, *) 'LOOPED', I
      END
