C     THE STATEMENT FUNCTION: A ONE-LINE FUNCTION IN THE DECLARATIONS.
C     OBSOLESCENT SINCE FORTRAN 95; SUPERSEDED BY INTERNAL FUNCTIONS.
      PROGRAM STF
      REAL AREA, R
      AREA(R) = 3.14159 * R * R
      WRITE (*, *) AREA(2.0)
      END
