C     VERSE 4, OLD TESTAMENT: THE COMMON BLOCK.
C     SHARED STORAGE BY POSITION, TRUSTED BY ALL, CHECKED BY NONE.
C     DECLARED OBSOLESCENT IN FORTRAN 2018.
      PROGRAM SHARING
      REAL TEMP, PRESS
      COMMON /STATE/ TEMP, PRESS
      TEMP = 288.15
      PRESS = 101.325
      CALL REPORT
      END
      SUBROUTINE REPORT
      REAL TEMP, PRESS
      COMMON /STATE/ TEMP, PRESS
      WRITE (*, *) 'T =', TEMP, ' P =', PRESS
      END
