C     VERSE 1, OLD TESTAMENT: THE SHAPE OF THE SOURCE.
C     LABELS LIVE IN COLUMNS 1-5, CONTINUATION MARKS IN COLUMN 6,
C     STATEMENTS IN COLUMNS 7 THROUGH 72. BEYOND 72, SILENCE.
      PROGRAM SHAPE
      INTEGER ANSWER
      ANSWER = 42
      WRITE (*, 100)
     &  ANSWER
  100 FORMAT ('THE ANSWER, RENDERED FROM COLUMN SEVEN: ', I2)
      END
