C     VERSE 5, OLD TESTAMENT: DOUBLE PRECISION BY DECREE.
C     (REAL*8, OFTEN SEEN IN THE WILD, WAS NEVER IN ANY STANDARD.)
      PROGRAM PRECISE
      DOUBLE PRECISION PI
      PI = 4.0D0 * ATAN(1.0D0)
      WRITE (*, '(F20.15)') PI
      END
