C     VERSE 2, OLD TESTAMENT: THE LABELED DO.
C     THE LOOP MARCHES TO A NUMBERED STATEMENT. OBSOLESCENT SINCE
C     FORTRAN 2018; ITS SHARED-LABEL COUSINS WERE DELETED OUTRIGHT.
      PROGRAM LOOPS
      INTEGER I, TOTAL
      TOTAL = 0
      DO 10 I = 1, 10
         TOTAL = TOTAL + I
   10 CONTINUE
      WRITE (*, *) 'TOTAL:', TOTAL
      END
