!> cathedral_pages: the assembly of one complete page. Head, masthead,
!> navigation, main, and footer are joined here; the route supplies the
!> metadata; the facts supply the footer's honest arithmetic.
module cathedral_pages
  use forty_util, only: string_t, push_string, int_to_str
  use cathedral_html, only: escape_html
  use cathedral_routes, only: route_t, append_nav
  use cathedral_facts, only: build_facts_t
  implicit none
  private
  public :: assemble_page

contains

  subroutine assemble_page(rt, body, facts, lines)
    type(route_t), intent(in) :: rt
    type(string_t), intent(in) :: body(:)
    type(build_facts_t), intent(in) :: facts
    type(string_t), allocatable, intent(out) :: lines(:)
    integer :: i

    allocate (lines(0))
    call push_string(lines, '<!doctype html>')
    call push_string(lines, '<html lang="en">')
    call push_string(lines, '<head>')
    call push_string(lines, '<meta charset="utf-8">')
    call push_string(lines, '<meta name="viewport" content="width=device-width, initial-scale=1">')
    call push_string(lines, '<meta name="description" content="' // &
                     escape_html(rt%description) // '">')
    call push_string(lines, '<meta name="generator" content="' // &
                     escape_html(facts%generator) // '">')
    call push_string(lines, '<title>' // escape_html(rt%title) // &
                     ' &#183; Fortran Cathedral</title>')
    call push_string(lines, '<link rel="icon" type="image/svg+xml" href="assets/ornament.svg">')
    call push_string(lines, '<link rel="stylesheet" href="assets/tokens.css">')
    call push_string(lines, '<link rel="stylesheet" href="assets/cathedral.css">')
    call push_string(lines, '</head>')
    call push_string(lines, '<body>')
    call push_string(lines, '<a class="skip" href="#main">Skip to content</a>')
    call push_string(lines, '<header class="masthead">')
    call push_string(lines, '  <img src="assets/ornament.svg" alt="" width="64" height="64">')
    call push_string(lines, '  <p class="site-title">Fortran Cathedral</p>')
    call push_string(lines, '  <p class="tagline">The web, as IBM never intended.</p>')
    call push_string(lines, '</header>')
    call append_nav(lines, rt%slug)
    call push_string(lines, '<main id="main">')
    call push_string(lines, '<h1>' // escape_html(rt%title) // '</h1>')
    do i = 1, size(body)
      call push_string(lines, body(i)%s)
    end do
    call push_string(lines, '</main>')
    call push_string(lines, '<footer>')
    call push_string(lines, '  <p>Generated by ' // escape_html(facts%generator) // &
                     ' &#183; Fortran files: ' // int_to_str(facts%fortran_files) // &
                     ' &#183; Heresy: ' // int_to_str(facts%heresy_lines) // &
                     ' executable lines &#183; JavaScript: 0 lines</p>')
    call push_string(lines, '  <p>The language is old. The arrays remain contiguous.</p>')
    call push_string(lines, '</footer>')
    call push_string(lines, '</body>')
    call push_string(lines, '</html>')
  end subroutine assemble_page

end module cathedral_pages
