!> cathedral_style: the design tokens and the stylesheet, both emitted
!> by Fortran. Restrained brutalism; Gothic structure; line-printer
!> devotion; readable contrast in dark and light observances.
module cathedral_style
  use forty_util, only: string_t, push_string
  implicit none
  private
  public :: tokens_css_lines, cathedral_css_lines, ACCENT_HEX

  character(*), parameter :: ACCENT_HEX = '#ffb000'

contains

  subroutine tokens_css_lines(lines)
    type(string_t), allocatable, intent(out) :: lines(:)
    allocate (lines(0))
    call push_string(lines, '/* EMITTED BY FORTY. THE DESIGN TOKENS OF THE CATHEDRAL. */')
    call push_string(lines, ':root {')
    call push_string(lines, '  --ground: #0f130f;')
    call push_string(lines, '  --panel: #161c16;')
    call push_string(lines, '  --ink: #e8e4d5;')
    call push_string(lines, '  --ink-dim: #b3ae9c;')
    call push_string(lines, '  --accent: ' // ACCENT_HEX // ';')
    call push_string(lines, '  --accent-2: #8fd98f;')
    call push_string(lines, '  --rule: #2e352e;')
    call push_string(lines, '  --measure: 70ch;')
    call push_string(lines, '  --space-1: 0.5rem;')
    call push_string(lines, '  --space-2: 1rem;')
    call push_string(lines, '  --space-3: 2rem;')
    call push_string(lines, '  --space-4: 3.5rem;')
    call push_string(lines, '  --font-liturgy: ui-monospace, "Cascadia Mono", Consolas, "Courier New", monospace;')
    call push_string(lines, '  --font-prose: Georgia, "Times New Roman", serif;')
    call push_string(lines, '}')
    call push_string(lines, '@media (prefers-color-scheme: light) {')
    call push_string(lines, '  :root {')
    call push_string(lines, '    --ground: #f4f1e6;')
    call push_string(lines, '    --panel: #ebe6d6;')
    call push_string(lines, '    --ink: #232819;')
    call push_string(lines, '    --ink-dim: #5c6152;')
    call push_string(lines, '    --accent: #8a5800;')
    call push_string(lines, '    --accent-2: #2e6b2e;')
    call push_string(lines, '    --rule: #cdc7b2;')
    call push_string(lines, '  }')
    call push_string(lines, '}')
  end subroutine tokens_css_lines

  subroutine cathedral_css_lines(lines)
    type(string_t), allocatable, intent(out) :: lines(:)
    allocate (lines(0))
    call push_string(lines, '/* EMITTED BY FORTY. THE STYLESHEET OF THE CATHEDRAL. */')
    call push_string(lines, '* { box-sizing: border-box; }')
    call push_string(lines, 'html { color-scheme: dark light; }')
    call push_string(lines, 'body {')
    call push_string(lines, '  margin: 0;')
    call push_string(lines, '  background: var(--ground);')
    call push_string(lines, '  color: var(--ink);')
    call push_string(lines, '  font-family: var(--font-prose);')
    call push_string(lines, '  font-size: 1.0625rem;')
    call push_string(lines, '  line-height: 1.6;')
    call push_string(lines, '}')
    call push_string(lines, '.skip { position: absolute; left: -999px; top: 0; }')
    call push_string(lines, '.skip:focus {')
    call push_string(lines, '  left: var(--space-2); top: var(--space-1); z-index: 9;')
    call push_string(lines, '  background: var(--accent); color: var(--ground);')
    call push_string(lines, '  padding: var(--space-1) var(--space-2);')
    call push_string(lines, '  font-family: var(--font-liturgy);')
    call push_string(lines, '}')
    call push_string(lines, '.masthead, nav, main, footer {')
    call push_string(lines, '  max-width: var(--measure);')
    call push_string(lines, '  margin-inline: auto;')
    call push_string(lines, '  padding-inline: var(--space-2);')
    call push_string(lines, '}')
    call push_string(lines, '.masthead { padding-top: var(--space-3); text-align: center; }')
    call push_string(lines, '.masthead img { display: block; margin: 0 auto var(--space-2); }')
    call push_string(lines, '.site-title {')
    call push_string(lines, '  font-family: var(--font-liturgy); text-transform: uppercase;')
    call push_string(lines, '  letter-spacing: 0.18em; font-size: 1.5rem; margin: 0;')
    call push_string(lines, '}')
    call push_string(lines, '.tagline {')
    call push_string(lines, '  font-family: var(--font-liturgy); text-transform: uppercase;')
    call push_string(lines, '  letter-spacing: 0.08em; font-size: 0.8rem;')
    call push_string(lines, '  color: var(--accent); margin: var(--space-1) 0 0;')
    call push_string(lines, '}')
    call push_string(lines, 'nav { margin-top: var(--space-2); }')
    call push_string(lines, 'nav ul {')
    call push_string(lines, '  list-style: none; display: flex; flex-wrap: wrap;')
    call push_string(lines, '  gap: var(--space-2); justify-content: center;')
    call push_string(lines, '  margin: 0; padding: var(--space-1) 0;')
    call push_string(lines, '  border-top: 1px solid var(--rule);')
    call push_string(lines, '  border-bottom: 1px solid var(--rule);')
    call push_string(lines, '}')
    call push_string(lines, 'nav a {')
    call push_string(lines, '  font-family: var(--font-liturgy); text-transform: uppercase;')
    call push_string(lines, '  letter-spacing: 0.1em; font-size: 0.85rem;')
    call push_string(lines, '  color: var(--ink); text-decoration: none; padding: 2px 4px;')
    call push_string(lines, '}')
    call push_string(lines, 'nav a:hover, nav a:focus-visible {')
    call push_string(lines, '  color: var(--accent); text-decoration: underline;')
    call push_string(lines, '  text-underline-offset: 4px;')
    call push_string(lines, '}')
    call push_string(lines, 'nav a[aria-current="page"] {')
    call push_string(lines, '  color: var(--accent); border-bottom: 2px solid var(--accent);')
    call push_string(lines, '}')
    call push_string(lines, 'main { padding-block: var(--space-3) var(--space-4); }')
    call push_string(lines, 'h1, h2 {')
    call push_string(lines, '  font-family: var(--font-liturgy); text-transform: uppercase;')
    call push_string(lines, '  letter-spacing: 0.12em; line-height: 1.25;')
    call push_string(lines, '}')
    call push_string(lines, 'h1 { font-size: 1.6rem; margin: 0 0 var(--space-2); }')
    call push_string(lines, 'h2 { font-size: 1.05rem; margin: var(--space-4) 0 var(--space-2); color: var(--accent); }')
    call push_string(lines, 'p { margin: 0 0 var(--space-2); }')
    call push_string(lines, 'ul, ol { margin: 0 0 var(--space-2); padding-left: 1.5rem; }')
    call push_string(lines, 'li { margin-bottom: var(--space-1); }')
    call push_string(lines, 'a { color: var(--accent-2); }')
    call push_string(lines, 'a:focus-visible { outline: 2px solid var(--accent); outline-offset: 2px; }')
    call push_string(lines, 'pre {')
    call push_string(lines, '  background: var(--panel); border: 1px solid var(--rule);')
    call push_string(lines, '  padding: var(--space-2); overflow-x: auto;')
    call push_string(lines, '  font-family: var(--font-liturgy); font-size: 0.85rem;')
    call push_string(lines, '  line-height: 1.5;')
    call push_string(lines, '}')
    call push_string(lines, 'pre.terminal { color: var(--accent-2); }')
    call push_string(lines, 'code { font-family: var(--font-liturgy); }')
    call push_string(lines, 'table { border-collapse: collapse; width: 100%; font-size: 0.95rem; }')
    call push_string(lines, 'caption {')
    call push_string(lines, '  font-family: var(--font-liturgy); text-transform: uppercase;')
    call push_string(lines, '  letter-spacing: 0.1em; font-size: 0.8rem; text-align: left;')
    call push_string(lines, '  margin-bottom: var(--space-1); color: var(--ink-dim);')
    call push_string(lines, '}')
    call push_string(lines, 'th, td {')
    call push_string(lines, '  border: 1px solid var(--rule);')
    call push_string(lines, '  padding: var(--space-1) var(--space-2); text-align: left;')
    call push_string(lines, '}')
    call push_string(lines, 'th {')
    call push_string(lines, '  font-family: var(--font-liturgy); text-transform: uppercase;')
    call push_string(lines, '  font-size: 0.75rem; letter-spacing: 0.08em;')
    call push_string(lines, '}')
    call push_string(lines, 'td.num { text-align: right; font-family: var(--font-liturgy); }')
    call push_string(lines, 'footer {')
    call push_string(lines, '  border-top: 1px solid var(--rule);')
    call push_string(lines, '  padding-block: var(--space-2) var(--space-3);')
    call push_string(lines, '  color: var(--ink-dim); font-size: 0.8rem;')
    call push_string(lines, '  font-family: var(--font-liturgy); text-transform: uppercase;')
    call push_string(lines, '  letter-spacing: 0.06em;')
    call push_string(lines, '}')
    call push_string(lines, 'footer p { margin: 0 0 var(--space-1); }')
    call push_string(lines, '@media (max-width: 40rem) {')
    call push_string(lines, '  body { font-size: 1rem; }')
    call push_string(lines, '  h1 { font-size: 1.3rem; }')
    call push_string(lines, '}')
    call push_string(lines, '@media (prefers-reduced-motion: reduce) {')
    call push_string(lines, '  * { transition: none !important; animation: none !important; }')
    call push_string(lines, '}')
  end subroutine cathedral_css_lines

end module cathedral_style
