!> cathedral_routes: the routes of the Cathedral and the navigation
!> carved from them. Routing is data owned by Fortran; pages, manifests,
!> and sitemaps are all derived from this single registry.
module cathedral_routes
  use forty_util, only: string_t, push_string
  implicit none
  private
  public :: route_t, routes, append_nav

  type :: route_t
    character(:), allocatable :: slug
    character(:), allocatable :: file
    character(:), allocatable :: title
    character(:), allocatable :: nav
    character(:), allocatable :: description
  end type route_t

contains

  !> The registry. Order here is the order of the nave's signage.
  function routes() result(rs)
    type(route_t), allocatable :: rs(:)
    allocate (rs(5))

    rs(1)%slug = 'nave'
    rs(1)%file = 'index.html'
    rs(1)%title = 'The Nave'
    rs(1)%nav = 'The Nave'
    rs(1)%description = 'A real website about Fortran, generated by Fortran. ' // &
                        'The web, as IBM never intended.'

    rs(2)%slug = 'why'
    rs(2)%file = 'why-it-still-stands.html'
    rs(2)%title = 'Why It Still Stands'
    rs(2)%nav = 'Why It Stands'
    rs(2)%description = 'Why Fortran remains load-bearing in scientific ' // &
                        'computing: arrays, compilers, validated code, ' // &
                        'foundational libraries, and institutional continuity.'

    rs(3)%slug = 'testaments'
    rs(3)%file = 'testaments.html'
    rs(3)%title = 'Old Testament / Modern Testament'
    rs(3)%nav = 'The Testaments'
    rs(3)%description = 'Fixed-form and modern Fortran side by side: five ' // &
                        'verses, two liturgies, one language. Every verse compiles.'

    rs(4)%slug = 'blas'
    rs(4)%file = 'book-of-blas.html'
    rs(4)%title = 'The Book of BLAS'
    rs(4)%nav = 'Book of BLAS'
    rs(4)%description = 'What BLAS is, why it became foundational, the three ' // &
                        'levels, and how LAPACK and higher ecosystems stand ' // &
                        'on it. Every exhibit computed by Fortran.'

    rs(5)%slug = 'confessional'
    rs(5)%file = 'confessional.html'
    rs(5)%title = 'The Confessional'
    rs(5)%nav = 'The Confessional'
    rs(5)%description = 'A public accounting of every non-Fortran impurity ' // &
                        'in the Fortran Cathedral. Executable heresy today: none.'
  end function routes

  !> Navigation with the active page marked for assistive technology
  !> and for the faithful alike.
  subroutine append_nav(lines, active_slug)
    type(string_t), allocatable, intent(inout) :: lines(:)
    character(*), intent(in) :: active_slug
    type(route_t), allocatable :: rs(:)
    integer :: i
    rs = routes()
    call push_string(lines, '<nav aria-label="Cathedral">')
    call push_string(lines, '  <ul>')
    do i = 1, size(rs)
      if (rs(i)%slug == active_slug) then
        call push_string(lines, '    <li><a href="' // rs(i)%file // &
                         '" aria-current="page">' // rs(i)%nav // '</a></li>')
      else
        call push_string(lines, '    <li><a href="' // rs(i)%file // '">' // &
                         rs(i)%nav // '</a></li>')
      end if
    end do
    call push_string(lines, '  </ul>')
    call push_string(lines, '</nav>')
  end subroutine append_nav

end module cathedral_routes
