!> cathedral_content: the inscriptions. Content is carved directly into
!> the generator, as befits a cathedral: the walls and the words are one
!> stone. Text with special characters passes through escape_html; the
!> code exhibit is quoted verbatim from Forty's own utilities.
!>
!> Accuracy discipline: every factual claim here is deliberately modest
!> and verifiable — 1957/IBM/Backus, Fortran 2023, the Fortran reference
!> implementations of BLAS and LAPACK, and Fortran's continuing role in
!> operational weather models such as ECMWF's IFS.
module cathedral_content
  use forty_util, only: string_t, push_string, int_to_str
  use cathedral_html, only: escape_html
  use cathedral_facts, only: build_facts_t
  use forty_confess, only: extract_hashes
  use cathedral_testaments, only: testaments_body
  use cathedral_why, only: why_body
  use cathedral_blas, only: blas_body
  use cathedral_hall, only: hall_body
  implicit none
  private
  public :: page_body

contains

  subroutine page_body(slug, facts, body, known)
    character(*), intent(in) :: slug
    type(build_facts_t), intent(in) :: facts
    type(string_t), allocatable, intent(out) :: body(:)
    logical, intent(out) :: known
    allocate (body(0))
    known = .true.
    select case (slug)
    case ('nave')
      call nave_body(facts, body)
    case ('why')
      call why_body(body)
    case ('testaments')
      call testaments_body(body, known)
    case ('blas')
      call blas_body(body, known)
    case ('hall')
      call hall_body(body, known)
    case ('confessional')
      call confessional_body(facts, body)
    case default
      known = .false.
    end select
  end subroutine page_body

  ! ------------------------------------------------------------- the nave

  subroutine nave_body(facts, body)
    type(build_facts_t), intent(in) :: facts
    type(string_t), allocatable, intent(inout) :: body(:)

    call para(body, 'This is a real website about Fortran, generated by a ' // &
      'static-site generator written in Fortran, operated by a Fortran ' // &
      'command-line verger named Forty. The absurdity is intentional. The ' // &
      'craftsmanship is not.')
    call para(body, 'Fortran is the oldest programming language still doing serious ' // &
      'daily work. This site honors that fact in the most direct way available: ' // &
      'by making Fortran do work nobody would reasonably assign to it, and doing ' // &
      'that work properly.')

    call push_string(body, '<pre class="terminal" aria-label="Build report">')
    call push_string(body, 'HOMEPAGE COMPILED.')
    call push_string(body, 'ROUTES RESOLVED: ' // int_to_str(facts%route_count) // '.')
    call push_string(body, 'FORTRAN SOURCE FILES: ' // int_to_str(facts%fortran_files) // '.')
    call push_string(body, 'EXECUTABLE HERESY: ' // int_to_str(facts%heresy_lines) // ' LINES.')
    call push_string(body, 'JAVASCRIPT SHIPPED: 0 LINES.')
    call push_string(body, 'CACHE LOCALITY: RIGHTEOUS.')
    call push_string(body, 'AWAITING PILGRIMS.')
    call push_string(body, '</pre>')

    call h2(body, 'Why it still stands')
    call para(body, 'Fortran was first delivered by IBM in 1957, from a team led by ' // &
      'John Backus, as a way to write mathematics for machines without writing ' // &
      'assembly. It is not a museum piece. The language remains a living ISO ' // &
      'standard — most recently Fortran 2023 — with modern modules, explicit ' // &
      'interfaces, allocatable arrays, and whole-array arithmetic.')
    call para(body, 'Much of numerical computing still rests on it. The reference ' // &
      'implementations of BLAS and LAPACK — the linear-algebra foundations ' // &
      'beneath a great deal of modern scientific software — are Fortran. Major ' // &
      'operational weather models, including ECMWF&#39;s IFS, are written ' // &
      'largely in Fortran. When the forecast arrives, an old and disciplined ' // &
      'language helped carry it.')
    call para(body, 'Fortran endures for unromantic reasons: arrays are first-class ' // &
      'citizens, aliasing rules favor aggressive compiler optimization, decades ' // &
      'of validated numerical code exist and still compile, and institutions do ' // &
      'not casually rewrite the software that predicts hurricanes.')

    call h2(body, 'The verger&#39;s hand')
    call para(body, 'The exhibit below is not a mock-up. It is a working function ' // &
      'quoted verbatim from this site&#39;s own build tool, Forty — modern, ' // &
      'free-form Fortran, escaped for your protection by another Fortran ' // &
      'function:')
    call trim_cr_exhibit(body)

    call h2(body, 'What stands so far')
    call para(body, 'This began as the smallest real cathedral: a nave, a ' // &
      'confessional, and the machinery that raised them. Fortran owns the ' // &
      'routing, the page assembly, the navigation, the stylesheet and its ' // &
      'design tokens, the rose window, the sitemap, the robots.txt, and the ' // &
      'route manifest. Four wings now stand: ' // &
      '<a href="why-it-still-stands.html">Why It Still Stands</a>, the ' // &
      'sourced case for Fortran&#39;s continued relevance; ' // &
      '<a href="testaments.html">Old Testament / Modern Testament</a>, where ' // &
      'fixed-form and modern Fortran are read side by side and every exhibit ' // &
      'compiles; <a href="book-of-blas.html">The Book of BLAS</a>, whose ' // &
      'arithmetic is computed by the generator itself; and ' // &
      '<a href="hall-of-deprecated-syntax.html">The Hall of Deprecated ' // &
      'Syntax</a>, where each retired feature bears the compiler&#39;s own ' // &
      'testimony. The Saints of Numerical Computing await their phase.')
    call para(body, 'The full accounting of this site&#39;s purity is public, in ' // &
      'the <a href="confessional.html">Confessional</a>.')
  end subroutine nave_body

  !> The trim_cr function, verbatim from src/forty_util.f90, escaped.
  subroutine trim_cr_exhibit(body)
    type(string_t), allocatable, intent(inout) :: body(:)
    type(string_t), allocatable :: src(:)
    integer :: i
    allocate (src(0))
    call push_string(src, '!> Strip trailing carriage returns and trailing blanks.')
    call push_string(src, '!> Captured command output on Windows deserves this courtesy.')
    call push_string(src, 'pure function trim_cr(s) result(r)')
    call push_string(src, '  character(*), intent(in) :: s')
    call push_string(src, '  character(:), allocatable :: r')
    call push_string(src, '  integer :: n')
    call push_string(src, '  n = len_trim(s)')
    call push_string(src, '  do while (n > 0)')
    call push_string(src, '    if (s(n:n) == achar(13)) then')
    call push_string(src, '      n = n - 1')
    call push_string(src, '    else')
    call push_string(src, '      exit')
    call push_string(src, '    end if')
    call push_string(src, '  end do')
    call push_string(src, '  r = s(1:n)')
    call push_string(src, 'end function trim_cr')
    call push_string(body, '<pre><code>' // escape_html(src(1)%s))
    do i = 2, size(src)
      call push_string(body, escape_html(src(i)%s))
    end do
    call push_string(body, '</code></pre>')
  end subroutine trim_cr_exhibit

  ! ------------------------------------------------------ the confessional

  subroutine confessional_body(facts, body)
    type(build_facts_t), intent(in) :: facts
    type(string_t), allocatable, intent(inout) :: body(:)

    call para(body, 'Every cathedral keeps its accounts. This page is the public ' // &
      'accounting of this repository&#39;s heresy, kept in two registers. ' // &
      '<strong>Necessary heresies</strong> are non-Fortran executable logic, or ' // &
      'external programs at genuine platform boundaries, that could not ' // &
      'reasonably be avoided; they are minimized, counted, and justified. ' // &
      '<strong>Committed heresies</strong> are avoidable violations — ' // &
      'operational mistakes, architectural lapses, residue admissions, or ' // &
      'failures to give Fortran work it could plausibly have owned. Correction ' // &
      'changes the status of a committed heresy. It does not erase it.')
    call para(body, 'The page is generated by the same Fortran that generates ' // &
      'everything else here, from the Heresy Ledger and from measurements ' // &
      'taken at build time.')

    call h2(body, 'The measurements')
    call push_string(body, '<table>')
    call push_string(body, '  <caption>Taken by Forty at generation time</caption>')
    call push_string(body, '  <thead>')
    call push_string(body, '    <tr><th scope="col">Measure</th><th scope="col">Value</th></tr>')
    call push_string(body, '  </thead>')
    call push_string(body, '  <tbody>')
    call fact_row(body, 'Fortran source files', int_to_str(facts%fortran_files))
    call fact_row(body, 'Executable heresy (nonblank lines)', int_to_str(facts%heresy_lines))
    call fact_row(body, 'Non-Fortran executable files', int_to_str(facts%heresy_files))
    call fact_row(body, 'Necessary executable impurities recorded', &
                  int_to_str(facts%n_necessary))
    call fact_row(body, 'Necessary platform boundaries recorded', &
                  int_to_str(size(facts%boundaries)))
    call fact_row(body, 'Committed heresies recorded', &
                  int_to_str(size(facts%committed)))
    call fact_row(body, 'Committed heresies unresolved', &
                  int_to_str(facts%n_unresolved))
    call fact_row(body, 'Committed heresies corrected or expiated', &
                  int_to_str(facts%n_corrected))
    call fact_row(body, 'JavaScript shipped to this page', '0 lines')
    call fact_row(body, 'Routes generated', int_to_str(facts%route_count))
    call fact_row(body, 'Generator', escape_html(facts%generator))
    call push_string(body, '  </tbody>')
    call push_string(body, '</table>')
    call para(body, 'The executable count is measured from the files themselves, ' // &
      'never inferred from the ledger, and committed heresies never alter it: ' // &
      'an event is not a line of code.')

    call h2(body, 'The executable register')
    call para(body, 'The Heresy Ledger currently records no executable non-Fortran ' // &
      'code. Every program in this repository — the site generator, the build ' // &
      'operator, the validators, the tests — is Fortran. The measurement above ' // &
      'is enforced twice: by the test suite, and by a validator that refuses ' // &
      'any generated page containing a script tag.')
    call para(body, 'HTML, CSS, SVG, XML, and JSON in this site are declarative ' // &
      'artifacts, all emitted by Fortran. They are output, not code.')

    call h2(body, 'The necessary platform boundaries')
    call para(body, 'The accounting is honest about its boundaries. These are ' // &
      'external programs at genuine platform seams — not heresy, and not ' // &
      'concealed. Forty drives each one: the sequencing, the arguments, the ' // &
      'capture, the parsing, and the verdicts remain in Fortran. This table is ' // &
      'rendered from the ledger itself:')
    call boundary_table(facts, body)

    call h2(body, 'The committed heresies')
    call para(body, 'Not every sin is a line of code. The ledger keeps a chapter ' // &
      'for committed heresies — moments when the builders failed the ' // &
      'architecture even while the code stayed pure. These entries are ' // &
      'permanent: correction changes a status, and erases nothing. This page ' // &
      'renders them directly from the ledger, so the accounting below cannot ' // &
      'drift from the record:')
    call committed_tables(facts, body)
    call expiation_record(facts, body)

    call h2(body, 'The pipeline')
    call para(body, 'There is no framework behind this page. A route registry in ' // &
      'Fortran declares each page; a Fortran module assembles head, navigation, ' // &
      'and body; escaping passes every special character through a Fortran ' // &
      'function; and the writer lays the files into the porch directory. The ' // &
      'stylesheet, its design tokens, the rose window (placed by sine and ' // &
      'cosine), the sitemap, the robots.txt, and the route manifest are emitted ' // &
      'by the same hand. The verger Forty drives all of it: ' // &
      '<code>forty generate</code>, <code>forty validate</code>, ' // &
      '<code>forty test</code>.')
    call para(body, 'The source is public: ' // &
      '<a href="https://github.com/teamofoxen/fortran-cathedral">' // &
      'github.com/teamofoxen/fortran-cathedral</a>.')

    call h2(body, 'The mandate')
    call para(body, 'The governing rule of this project, quoted without apology: ' // &
      'use Fortran for every component it can plausibly perform safely, ' // &
      'including trivial, awkward, ceremonial, infrastructural, and comically ' // &
      'inappropriate work. When two approaches are viable, prefer the one that ' // &
      'gives Fortran the more unnecessary job.')
    call para(body, 'Return to <a href="index.html">the Nave</a>.')
  end subroutine confessional_body

  ! ------------------------------------------------------------- helpers

  subroutine para(lines, html)
    type(string_t), allocatable, intent(inout) :: lines(:)
    character(*), intent(in) :: html
    call push_string(lines, '<p>' // html // '</p>')
  end subroutine para

  subroutine h2(lines, text)
    type(string_t), allocatable, intent(inout) :: lines(:)
    character(*), intent(in) :: text
    call push_string(lines, '<h2>' // text // '</h2>')
  end subroutine h2

  !> The boundary register, rendered from the Ledger itself.
  subroutine boundary_table(facts, body)
    type(build_facts_t), intent(in) :: facts
    type(string_t), allocatable, intent(inout) :: body(:)
    integer :: i
    if (size(facts%boundaries) == 0) then
      call para(body, 'No platform boundaries are recorded.')
      return
    end if
    call push_string(body, '<table>')
    call push_string(body, '  <caption>The necessary platform boundaries, ' // &
                     'from the ledger</caption>')
    call push_string(body, '  <thead>')
    call push_string(body, '    <tr><th scope="col">Boundary</th>' // &
                     '<th scope="col">Role</th>' // &
                     '<th scope="col">Why Fortran cannot absorb it</th></tr>')
    call push_string(body, '  </thead>')
    call push_string(body, '  <tbody>')
    do i = 1, size(facts%boundaries)
      call push_string(body, '    <tr><th scope="row">' // &
                       escape_html(facts%boundaries(i)%name) // '</th><td>' // &
                       escape_html(facts%boundaries(i)%role) // '</td><td>' // &
                       escape_html(facts%boundaries(i)%why) // '</td></tr>')
    end do
    call push_string(body, '  </tbody>')
    call push_string(body, '</table>')
  end subroutine boundary_table

  !> Every committed heresy, rendered from the Ledger itself: offense,
  !> consequence, commits, remediation, evidence, and status.
  subroutine committed_tables(facts, body)
    type(build_facts_t), intent(in) :: facts
    type(string_t), allocatable, intent(inout) :: body(:)
    integer :: i
    if (size(facts%committed) == 0) then
      call para(body, 'No committed heresies are recorded.')
      return
    end if
    do i = 1, size(facts%committed)
      call push_string(body, '<table>')
      call push_string(body, '  <caption>Committed heresy ' // int_to_str(i) // &
                       ' of ' // int_to_str(size(facts%committed)) // ' — ' // &
                       escape_html(facts%committed(i)%title) // '</caption>')
      call push_string(body, '  <tbody>')
      call trans_row(body, 'Date', escape_html(facts%committed(i)%date))
      call trans_row(body, 'Offense', escape_html(facts%committed(i)%offense))
      call trans_row(body, 'Consequence', &
                     escape_html(facts%committed(i)%consequence))
      call trans_row(body, 'Executable non-Fortran lines introduced', &
                     escape_html(facts%committed(i)%exec_lines))
      call trans_row(body, 'Offense commits', &
                     commits_cell(facts%committed(i)%offense_commits))
      call trans_row(body, 'Remediation', &
                     escape_html(facts%committed(i)%remediation))
      call trans_row(body, 'Evidence commits', &
                     commits_cell(facts%committed(i)%evidence_commits))
      call trans_row(body, 'Status', escape_html(facts%committed(i)%status))
      call push_string(body, '  </tbody>')
      call push_string(body, '</table>')
    end do
  end subroutine committed_tables

  !> A ledger commits cell, made visible: each hash robed in code tags;
  !> a hashless cell (a supervisory offense) is shown as its own words.
  function commits_cell(text) result(html)
    character(*), intent(in) :: text
    character(:), allocatable :: html
    type(string_t), allocatable :: hashes(:)
    integer :: i
    call extract_hashes(text, hashes)
    if (size(hashes) == 0) then
      html = escape_html(text)
      return
    end if
    html = ''
    do i = 1, size(hashes)
      if (i > 1) html = html // ' '
      html = html // '<code>' // escape_html(hashes(i)%s) // '</code>'
    end do
  end function commits_cell

  !> The restitution, when one has been performed: rendered from the
  !> Ledger's expiation record. The offense is not softened; the means
  !> of its expiation are stated exactly.
  subroutine expiation_record(facts, body)
    type(build_facts_t), intent(in) :: facts
    type(string_t), allocatable, intent(inout) :: body(:)
    if (.not. facts%expiated) return
    call para(body, 'The stain above has been expiated by restitution. Forty ' // &
      'withdrew the manually presented tree with a forward-only commit, then ' // &
      'presented the canonical tree anew by his own hand, and advanced the ' // &
      'branch without force and without rewriting. The transgression itself ' // &
      'remains in history, unerased, as the record demands:')
    call push_string(body, '<table>')
    call push_string(body, '  <caption>The expiation record</caption>')
    call push_string(body, '  <tbody>')
    call trans_row(body, 'Expiated transgression', '<code>' // &
                   escape_html(facts%expiation%offender) // '</code>')
    call trans_row(body, 'Withdrawal commit', '<code>' // &
                   escape_html(facts%expiation%withdrawal) // '</code>')
    call trans_row(body, 'Canonical re-offering commit', '<code>' // &
                   escape_html(facts%expiation%reoffering) // '</code>')
    call trans_row(body, 'Means', escape_html(facts%expiation%means))
    call trans_row(body, 'History', escape_html(facts%expiation%history))
    call push_string(body, '  </tbody>')
    call push_string(body, '</table>')
  end subroutine expiation_record

  subroutine trans_row(lines, measure, value_html)
    type(string_t), allocatable, intent(inout) :: lines(:)
    character(*), intent(in) :: measure, value_html
    call push_string(lines, '    <tr><th scope="row">' // measure // &
                     '</th><td>' // value_html // '</td></tr>')
  end subroutine trans_row

  subroutine fact_row(lines, measure, value)
    type(string_t), allocatable, intent(inout) :: lines(:)
    character(*), intent(in) :: measure, value
    call push_string(lines, '    <tr><th scope="row">' // measure // &
                     '</th><td class="num">' // value // '</td></tr>')
  end subroutine fact_row

end module cathedral_content
